### ISSUE TITLE
The system is not robust enough

### ISSUE THREAD

**Issue by Yanguangchen** [kdickerson/automatonSimulator#11]
some DFA that can be accepts a certain strings, are not accepted when tested for finite automata tester
![image](https://github.com/kdickerson/automatonSimulator/assets/83961207/1ae4ced5-7435-41d5-9404-8c0cd9ae8d22)

for example the second string 11101 should be accepted but results show it got rejected

**Comment by kdickerson** [comment]
I'm not sure what's happening for you.  First, that's not a valid DFA as it has 2 transitions from state `A` on symbol `1`.  The application shouldn't allow you to create an invalid DFA, so I presume that's actually an NFA.  If the application thinks it actually is a DFA, then it's undefined behavior.

When I recreate the same NFA it's behaving as expected:
![nfa-example](https://github.com/kdickerson/automatonSimulator/assets/774044/fc72b38f-767e-4062-b7a0-f0ccfa8caccf)

Which is this NFA:
```
{"type":"NFA","nfa":{"transitions":{"start":{"0":["s0"],"1":["start"]},"s0":{"1":["s1","s0"]},"s1":{"0":["s0"],"1":["start"]}},"startState":"start","acceptStates":["s1"]},"states":{"start":{},"s0":{"top":210,"left":252,"displayId":"A"},"s1":{"isAccept":true,"top":359,"left":468,"displayId":"B"}},"transitions":[{"stateA":"start","label":"0","stateB":"s0"},{"stateA":"start","label":"1","stateB":"start"},{"stateA":"s0","label":"1","stateB":"s1"},{"stateA":"s0","label":"1","stateB":"s0"},{"stateA":"s1","label":"0","stateB":"s0"},{"stateA":"s1","label":"1","stateB":"start"}],"bulkTests":{"accept":"1011\n010101\n11101","reject":""}}
```

**Comment by Yanguangchen** [comment]
apologies, didnt see the NFA button
