### ISSUE TITLE
Feature Request: Support for adding states by double-clicking on the workspace.

### ISSUE THREAD

**Issue by albinkc** [kdickerson/automatonSimulator#2]
It would make it faster to add new states as double-click is currently not used for anything else.

If possible, add new state where double-click was performed.

**Comment by kdickerson** [comment]
That does sound useful.  I'll try to add it next time I have time to work on this.

**Comment by kdickerson** [comment]
Added and deployed.  Double-clicking on the workspace will create a new state at that location.

**Comment by albinkc** [comment]
Wow! This is like the quickest request to deploy I've ever seen. Kudos.
