### ISSUE TITLE
PDA accepted strings

### ISSUE THREAD

**Issue by memen45** [kdickerson/automatonSimulator#4]
First of all, very nice ui for these automata! It makes testing an automaton much easier!

I am missing the feature to change the acceptance mode. For the PushDown Automata the default mode of acceptance seems to be the empty input string (&& machine should be in acceptance state), but there are situations where acceptance is extended by the condition that the stack needs to be empty as well.

Is it possible to add this functionality? Or is it already somewhere hidden?

Best regards,

**Comment by kdickerson** [comment]
The formal definition of a PDA does not provide the ability to detect an
empty stack. To enforce that condition on your PDA you should push a
sentinel value on to the stack. Then your machine should only transition to
an accept state upon popping the sentinel value from the stack. This will
ensure the stack is empty when in the accept state.

Though I recognize that such a feature would be convenient, I'm not sure I
want to modify the code away from the formal definition. The use of
sentinel values is an important device and providing a shortcut around this
common use case may do a disservice to students trying to understand how to
create PDAs.

**Comment by memen45** [comment]
Thanks for the complete and clear answer! The workaround seems to be functional, although it complicates the diagram a little. 
It works exactly as expected with the # first on the stack!
