### ISSUE TITLE
DFA Bug?

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [kdickerson/automatonSimulator#5]
Why this DFA can not pass `aaa`?

![Screenshot from 2019-05-05 12-04-25](https://user-images.githubusercontent.com/28505034/57192187-f704a900-6f2d-11e9-88fc-614ab0fc64b1.png)

**Comment by kdickerson** [comment]
Hmmmm.... it does look like it should pass.

Are you sure you don't have a space after 'aaa' so it's really trying to
pass 'aaa '?

Can you copy/paste the machine definition string here so I can try it
myself? (Use the 'save' menu, the arrow going into the box.)

Also, have you used the step-through debugger to see why it's not ending on
the accept state?

**Comment by cakebytheoceanLuo** [comment]
Hmm Solved.  
Some edges in not saved, although them are showed in the canvas.
